-- Execute este ficheiro uma vez no SQL Editor do seu projeto Supabase.
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  description text not null,
  icon text not null default 'cpu',
  price_from numeric(10,2),
  price_mode text not null default 'quote' check (price_mode in ('fixed','from','quote')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.availability_slots (
  id bigint generated by default as identity primary key,
  date date not null,
  time text not null,
  status text not null default 'available' check (status in ('available','blocked','booked')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(date, time)
);
create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_phone text,
  customer_email text,
  summary text not null,
  estimate numeric(10,2),
  status text not null default 'new' check (status in ('new','contacted','closed')),
  created_at timestamptz not null default now()
);
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.availability_slots(id),
  date date not null,
  time text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  service_summary text,
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.services enable row level security;
alter table public.availability_slots enable row level security;
alter table public.quotes enable row level security;
alter table public.bookings enable row level security;
drop policy if exists "public can read active services" on public.services;
create policy "public can read active services" on public.services for select using (active = true);
drop policy if exists "public can read open slots" on public.availability_slots;
create policy "public can read open slots" on public.availability_slots for select using (status = 'available');

-- Permite que o cliente receba atualizações em tempo real.
alter publication supabase_realtime add table public.services;
alter publication supabase_realtime add table public.availability_slots;
alter publication supabase_realtime add table public.bookings;

insert into public.services (slug, name, category, description, icon, price_from, price_mode)
values
  ('informatica', 'Manutenção de computadores', 'Informática', 'Hardware, software, limpeza, formatação, upgrades e otimização.', 'cpu', 120, 'from'),
  ('games', 'Desbloqueio & games', 'Entretenimento digital', 'Desbloqueio de consoles e instalação de bibliotecas de jogos.', 'gamepad-2', 180, 'from'),
  ('ponto', 'Ponto eletrônico', 'Gestão de ponto', 'Relógios cartográficos, Control iD e apoio no fechamento de folha.', 'timer-reset', 150, 'from'),
  ('consultoria', 'RHiD & Secullum Web', 'Consultoria', 'Consultoria prática para fechamento e organização do RH.', 'workflow', 200, 'from'),
  ('cameras', 'Câmeras de segurança', 'Segurança eletrônica', 'Instalação, configuração e orientação para monitoramento.', 'camera', null, 'quote'),
  ('externos', 'Serviços externos', 'Manutenção geral', 'Poda de árvores de pequeno porte e reparos diversos.', 'trees', 100, 'from')
on conflict (slug) do nothing;
